format = """
$time\
$hostname\
$directory\
[\n-> ](fg:#d00b0b)\
"""

add_newline = true

[username]
show_always = true
style_user = "fg:#d00b0b"
style_root = "fg:#d00b0b"
format = '[$user ]($style)'

[hostname]
ssh_only = true
format = "[ • ](fg:#ff9900)[$hostname]($style)"
trim_at = ""
style = "fg:#d00b0b"
disabled = false

[directory]
style = "fg:#ff9900"
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "…/"

# [directory.substitutions]
# "Documents" = " "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "

[time]
disabled = false
style = "fg:#d00b0b"
time_format = "%H:%M:%S"
format = '[[$time](fg:#d00b0b)]($style)'
